# Generated by Django 5.2.6 on 2025-10-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalAdopcion',
        ),
    ]
