# Generated by Django 5.2.7 on 2025-11-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='raza',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sexo',
        ),
        migrations.AddField(
            model_name='animal',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('adoptado', 'Adoptado')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='animales_adopcion/'),
        ),
    ]
