# Generated by Django 5.2.7 on 2025-11-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_remove_animal_edad_remove_animal_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='genero',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='tamano',
            field=models.CharField(blank=True, choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=50, null=True),
        ),
    ]
