# Generated by Django 5.2.6 on 2025-11-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0005_animal_color_animal_genero_animal_tamano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/domicilios/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='ine',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/ines/'),
        ),
    ]
