# Generated by Django 5.2.8 on 2025-11-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_animal_comprobante_domicilio_animal_ine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='comprobante_domicilio',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ine',
        ),
    ]
