# Generated by Django 5.2.8 on 2025-11-11 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Título/Nombre')),
                ('tipo', models.CharField(choices=[('AVISO', 'Aviso'), ('NOTICIA', 'Noticia'), ('OTRO', 'Otro')], default='AVISO', max_length=10, verbose_name='Tipo de Publicación')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones (Avisos/Servicios)',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
