# Generated by Django 5.2.6 on 2025-11-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Término'),
        ),
    ]
