# Generated by Django 5.2.6 on 2025-11-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/domicilios/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ine',
            field=models.FileField(blank=True, null=True, upload_to='solicitudes/ines/'),
        ),
    ]
