# Generated by Django 5.2.6 on 2025-11-03 03:28

from django.db import migrations

# Esta es la lista de categorías que querías
CATEGORIAS_INICIALES = [
    "Alimento",
    "Juguetes",
    "Salud",
    "Higiene y Aseo",
    "Accesorios",
    "Otro"
]

def cargar_categorias(apps, schema_editor):
    # Obtenemos el modelo 'Categoria' de la app 'productos'
    Categoria = apps.get_model('productos', 'Categoria')
    
    # Creamos un objeto Categoria por cada nombre en la lista
    for nombre_cat in CATEGORIAS_INICIALES:
        Categoria.objects.create(nombre=nombre_cat)

class Migration(migrations.Migration):

    # Esta migración depende de la anterior (la que creó el modelo)
    dependencies = [
        ('productos', '0002_categoria_producto_categoria'), # Ajusta '0002' al nombre de tu migración anterior
    ]

    operations = [
        # Ejecutamos la función que definimos arriba
        migrations.RunPython(cargar_categorias),
    ]